### PR TITLE
feat(spec): Add schema types

### PR DESCRIPTION
**Pull request by Xuanwo**
This PR will add schema types. The parse for `DataType` is not implemented yet.

### CODE REVIEW

**Review by JingsongLi — APPROVED** [review]
+1

**Comment by JingsongLi** [comment]
@Xuanwo Please resolve conflicts.

**Comment by Xuanwo** [comment]
> @Xuanwo Please resolve conflicts.

Will do

**Comment by Xuanwo** [comment]
DONE, @JingsongLi PTAL, thanks!

**Comment by JingsongLi** [comment]
+1

**Pull request merged**
